name: Main Workflow
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  check:
    name: Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: docker/setup-buildx-action@v2

      - name: Setup Go 1.21.1
        uses: actions/setup-go@v4
        with:
          go-version: '1.21.1'

      - name: Build images
        timeout-minutes: 10
        run: docker compose build

      - name: Run containers
        timeout-minutes: 5
        run: |
          docker compose up -d
          ./scripts/wait-script.sh
        env:
          WAIT_PORTS: 8080,8070,8060,8050

      - name: Run Unit Tests
        run: |
          go test ./src/library-service/handler
          go test ./src/reservation-service/handler
          go test ./src/rating-service/handler

      - name: Run API Tests
        uses: matt-ball/newman-action@master
        with:
          collection: tests/postman/collection.json
          environment: tests/postman/environment.json
          delayRequest: 100
          reporters: '[ "cli" ]'

      - name: Stop containers
        if: always()
        continue-on-error: true
        run: docker compose down -v